import { drizzle } from "drizzle-orm/expo-sqlite"
import { openDatabaseSync } from "expo-sqlite"
import { useEffect, useState } from "react"

import * as schema from "./schema"

/**
 * Synchronous SQLite handle. Opened lazily and reused across the app.
 * `enableChangeListener: true` lets drizzle's `useLiveQuery` reflect row
 * changes without a manual refetch.
 */
const sqlite = openDatabaseSync("honestea.db", {
  enableChangeListener: true,
})

export const db = drizzle(sqlite, { schema })

export type Db = typeof db

/**
 * Phase 1 migration. Inlined instead of imported from `drizzle/0000_*.sql`
 * because Metro/Babel choke on raw .sql imports — `babel-plugin-inline-import`
 * doesn't reliably substitute before Metro walks into the file. The .sql
 * files generated by `drizzle-kit` stay in the repo as source-of-truth /
 * for diffing future schema changes; only the runtime side is hand-mirrored
 * here. When this list grows past two or three migrations we'll switch to
 * a real ladder.
 *
 * `IF NOT EXISTS` makes this idempotent so re-running on every launch is
 * cheap and safe.
 */
const MIGRATION_V1 = `
CREATE TABLE IF NOT EXISTS conversations (
  id text PRIMARY KEY NOT NULL,
  user_id text,
  title text,
  model_id text NOT NULL,
  archived integer DEFAULT 0 NOT NULL,
  synced_at integer,
  created_at integer NOT NULL,
  updated_at integer NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id text PRIMARY KEY NOT NULL,
  conversation_id text NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  model_id text,
  prompt_tokens integer,
  completion_tokens integer,
  cost_cents integer,
  status text DEFAULT 'complete' NOT NULL,
  created_at integer NOT NULL,
  FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON UPDATE no action ON DELETE cascade
);
`

/**
 * v2: starred flag for the triple-dot menu's pin/star action. Idempotent
 * via a column-existence check (sqlite ALTER TABLE doesn't have IF NOT
 * EXISTS for ADD COLUMN).
 */
function applyMigrationV2() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(conversations);",
  )
  const hasStarred = cols.some((c) => c.name === "starred")
  if (!hasStarred) {
    sqlite.execSync(
      "ALTER TABLE conversations ADD COLUMN starred integer DEFAULT 0 NOT NULL;",
    )
  }
}

/**
 * v3: cost precision + regenerate cost-rolling.
 *  - `cost_usd REAL` lets us store the real OpenRouter `usage.cost` float
 *    (typical Haiku turn ≈ $0.0003 — integer cents rounded everything up
 *    to $0.010 because of `Math.ceil(usd * 100)`).
 *  - `superseded_at INTEGER` marks an assistant turn that was replaced by a
 *    regenerate. UI hides them, send-path skips them, but the cost sum
 *    still includes them so trailing conversation cost rolls forward.
 */
function applyMigrationV3() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasCostUsd = cols.some((c) => c.name === "cost_usd")
  if (!hasCostUsd) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN cost_usd real;")
  }
  const hasSupersededAt = cols.some((c) => c.name === "superseded_at")
  if (!hasSupersededAt) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN superseded_at integer;")
  }
}

/**
 * v4: compaction support.
 *  - `summarized_at INTEGER` marks a row that was rolled into a summary.
 *    Hidden in UI + skipped from send-path; cost still counts.
 *  - `summarized_into TEXT` FK to the synthetic summary row that replaces
 *    this one in the model context.
 *  - `kind TEXT` — "normal" (default) or "summary". The send-path keeps
 *    summary rows as system-role messages in the prompt; the chat view
 *    hides them and renders a divider where they sit.
 */
function applyMigrationV4() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasSummarizedAt = cols.some((c) => c.name === "summarized_at")
  if (!hasSummarizedAt) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN summarized_at integer;")
  }
  const hasSummarizedInto = cols.some((c) => c.name === "summarized_into")
  if (!hasSummarizedInto) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN summarized_into text;")
  }
  const hasKind = cols.some((c) => c.name === "kind")
  if (!hasKind) {
    sqlite.execSync(
      "ALTER TABLE messages ADD COLUMN kind text DEFAULT 'normal' NOT NULL;",
    )
  }
}

/**
 * v5: route provenance.
 *  - `provider TEXT` records which backend an assistant turn was actually
 *    sent to. Lets the UI render "via OpenRouter" / "via Anthropic"
 *    accurately even after the user removes the direct key.
 */
function applyMigrationV5() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasProvider = cols.some((c) => c.name === "provider")
  if (!hasProvider) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN provider text;")
  }
}

/**
 * v6: web search citations.
 *  - `citations TEXT` JSON-encoded `Citation[]` from OR's
 *    `annotations[].url_citation`. Null when no search ran. Drives the
 *    "🌐 N sources" chip on assistant messages.
 */
function applyMigrationV6() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasCitations = cols.some((c) => c.name === "citations")
  if (!hasCitations) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN citations text;")
  }
}

/**
 * v7: user-attached images/files on user messages.
 *  - `attachments TEXT` JSON-encoded `Attachment[]`. Null on assistant +
 *    system rows + user rows that had no attachments. Drives image
 *    rendering inside user bubbles.
 */
function applyMigrationV7() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasAttachments = cols.some((c) => c.name === "attachments")
  if (!hasAttachments) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN attachments text;")
  }
}

/**
 * v8: persisted server-tool calls per assistant turn.
 *  - `tool_calls TEXT` JSON-encoded `PersistedToolCall[]`. Null on
 *    user/system rows + assistant rows that didn't run any server tools.
 *    Lets the chat history render the expandable "Searched the web"
 *    panel after streaming completes.
 */
function applyMigrationV8() {
  const cols = sqlite.getAllSync<{ name: string }>(
    "PRAGMA table_info(messages);",
  )
  const hasToolCalls = cols.some((c) => c.name === "tool_calls")
  if (!hasToolCalls) {
    sqlite.execSync("ALTER TABLE messages ADD COLUMN tool_calls text;")
  }
}

/**
 * v9: immutable usage ledger.
 *  - New `usage_events` table — one row per completed assistant turn,
 *    capturing tokens / cost / model at completion time. Deliberately
 *    not a foreign key to `messages` so deleting a chat doesn't rewrite
 *    historical usage totals.
 *  - Backfill from existing assistant messages. Deterministic event id
 *    (`evt-{messageId}`) makes the backfill idempotent — re-running on
 *    every launch is a no-op once events exist.
 */
function applyMigrationV9() {
  sqlite.execSync(`
    CREATE TABLE IF NOT EXISTS usage_events (
      id text PRIMARY KEY NOT NULL,
      model_id text NOT NULL,
      provider text NOT NULL,
      prompt_tokens integer NOT NULL,
      completion_tokens integer NOT NULL,
      cost_usd real NOT NULL,
      created_at integer NOT NULL,
      message_id text
    );
  `)
  // Backfill: copy every assistant message that has token data into the
  // ledger. INSERT OR IGNORE on a deterministic id makes this safe to
  // re-run — the migration ladder fires on every launch.
  sqlite.execSync(`
    INSERT OR IGNORE INTO usage_events (
      id, model_id, provider, prompt_tokens, completion_tokens,
      cost_usd, created_at, message_id
    )
    SELECT
      'evt-' || messages.id,
      COALESCE(model_id, 'unknown'),
      COALESCE(provider, 'openrouter'),
      prompt_tokens,
      completion_tokens,
      COALESCE(cost_usd, 0),
      created_at,
      id
    FROM messages
    WHERE role = 'assistant'
      AND prompt_tokens IS NOT NULL
      AND completion_tokens IS NOT NULL;
  `)
}

let migrated = false

function applyMigrations() {
  if (migrated) return
  sqlite.execSync(MIGRATION_V1)
  applyMigrationV2()
  applyMigrationV3()
  applyMigrationV4()
  applyMigrationV5()
  applyMigrationV6()
  applyMigrationV7()
  applyMigrationV8()
  applyMigrationV9()
  migrated = true
}

/**
 * Drop-in replacement for drizzle's `useMigrations(db, migrations)` — same
 * `{ success, error }` contract so the root layout migration gate doesn't
 * need to change.
 */
export function useRunMigrations(): {
  success: boolean
  error: Error | undefined
} {
  const [state, setState] = useState<{ success: boolean; error: Error | undefined }>(
    { success: migrated, error: undefined },
  )

  useEffect(() => {
    if (state.success) return
    try {
      applyMigrations()
      setState({ success: true, error: undefined })
    } catch (e) {
      setState({
        success: false,
        error: e instanceof Error ? e : new Error("Migration failed"),
      })
    }
  }, [state.success])

  return state
}
